using System;

namespace SmartTour.Mobile.Services;

public class LanguageService
{
    public string SelectedLanguage { get; private set; } = "vi";
    public event Action? OnLanguageChanged;

    // Từ điển chứa tất cả bản dịch UI
    private readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["vi"] = new(StringComparer.OrdinalIgnoreCase) {
            ["Home"] = "Trang Chủ",
            ["Hello"] = "Xin chào",
            ["SearchHint"] = "Hôm nay bạn muốn đi đâu?",
            ["Categories"] = "Danh mục phổ biến",
            ["All"] = "Tất cả",
            ["Featured"] = "Địa điểm nổi bật",
            ["SeeAll"] = "Xem tất cả",
            ["FindAround"] = "Tìm quanh đây:",
            ["Details"] = "Chi tiết",
            ["NoResults"] = "Chưa tìm thấy địa điểm",
            ["EndList"] = "Hết danh sách",
            ["Map"] = "Bản đồ",
            ["Profile"] = "Cá nhân",
            ["Scan"] = "Quét QR",
            ["Logout"] = "Thoát",
            ["Login"] = "Đăng nhập",
            ["Introduction"] = "Giới thiệu",
            ["OpeningHours"] = "Giờ mở cửa",
            ["Location"] = "Vị trí",
            ["Direction"] = "Dẫn đường",
            ["Audio"] = "Thuyết minh",
            ["Share"] = "Chia sẻ",
            ["Favorite"] = "Yêu thích",
            ["StartJourney"] = "BẮT ĐẦU HÀNH TRÌNH",
            ["Updating"] = "Đang cập nhật nội dung...",
            ["ViewOnMap"] = "Xem trên bản đồ",
            ["Coordinates"] = "Tọa độ",
            ["Place"] = "Địa điểm",
            // Danh mục từ API
            ["Khác"] = "Khác",
            ["Quán Bar/Pub"] = "Quán Bar/Pub",
            ["Quán Bar/Club"] = "Quán Bar/Club",
            ["Quán ăn nhanh"] = "Quán ăn nhanh",
            ["Nhà hàng"] = "Nhà hàng",
            ["Cà phê"] = "Cà phê",
            // Auto-Play
            ["AutoPlayTitle"] = "Tự động thuyết minh",
            ["AutoPlayDesc"] = "Tự động phát khi đến gần địa điểm",
            // Days
            ["Monday"] = "Thứ 2",
            ["Tuesday"] = "Thứ 3",
            ["Wednesday"] = "Thứ 4",
            ["Thursday"] = "Thứ 5",
            ["Friday"] = "Thứ 6",
            ["Saturday"] = "Thứ 7",
            ["Sunday"] = "Chủ Nhật",
            ["Narrating"] = "Đang thuyết minh...",
            ["NearbyArea"] = "Bạn đang ở gần",
            ["Replay"] = "Nghe lại",
            ["ToggleAutoPlay"] = "Tự động phát",
            ["FavoriteList"] = "Danh sách quán yêu thích",
            ["JoinDate"] = "Ngày tham gia",
            ["Active"] = "Đang hoạt động",
            ["PersonalInfo"] = "Thông tin cá nhân",
            ["Preferences"] = "Cài đặt & Tùy chỉnh",
            ["Privacy"] = "Quyền riêng tư",
            ["Support"] = "Trung tâm hỗ trợ",
            ["ChangeAvatarHint"] = "Nhấn máy ảnh để thay đổi ảnh đại diện",
            ["FullNameLabel"] = "Họ và tên",
            ["FullNameHint"] = "Tên của bạn sẽ hiển thị trên hồ sơ và đánh giá.",
            ["EmailLabel"] = "Email",
            ["SaveChange"] = "Lưu thay đổi",
            ["Saving"] = "Đang lưu...",
            ["LockEmailHint"] = "Email không thể thay đổi để đảm bảo bảo mật.",
            ["Badges"] = "Huy hiệu",
            ["EmptyFavs"] = "Chưa có địa điểm yêu thích",
            ["AppSettings"] = "Cài đặt ứng dụng",
            ["LoadingMap"] = "Đang tải bản đồ",
            ["WaitMoment"] = "Vui lòng chờ giây lát...",
            ["MapLoadError"] = "Không thể tải bản đồ",
            ["Retry"] = "Thử lại",
            ["TokenMissing"] = "Token Mapbox không tồn tại.",
            ["LoginToSave"] = "Bạn cần đăng nhập để lưu địa điểm này",
            ["LoginNow"] = "Đăng nhập ngay",
            ["SavedToFavs"] = "Đã lưu vào danh sách yêu thích",
            ["RemovedFromFavs"] = "Đã bỏ lưu",
            ["LoadPoiError"] = "Không thể tải thông tin địa điểm",
            ["SavePoiError"] = "Lỗi khi lưu địa điểm",
            ["AudioPlayError"] = "Lỗi phát âm thanh",
            ["Listen"] = "Nghe",
            ["QRHint"] = "Đưa mã QR vào khung ngắm để tự động nhận diện",
            ["CameraUnavailable"] = "Camera không khả dụng",
            ["QRLoadError"] = "Lỗi tải nội dung QR",
            ["CameraPermission"] = "Vui lòng cấp quyền Camera để quét thẻ QR.",
            ["QROpenError"] = "Mở QR thất bại",
            ["QRMismatch"] = "Mã QR hệ thống không khớp",
            ["QRNoPoi"] = "Không tìm thấy nội dung tương ứng với QR.",
            ["BannerPlaying"] = "🔊 Đang thuyết minh",
            ["BannerNear"] = "📍 Bạn đang ở gần",
            // Auth
            ["WelcomeTitle"] = "Chào mừng bạn!",
            ["LoginSubtitle"] = "Đăng nhập để khám phá các địa điểm tuyệt vời",
            ["Processing"] = "Đang xử lý...",
            ["LoginWithGoogle"] = "Đăng nhập bằng Google",
            ["Or"] = "HOẶC",
            ["ExploreAsGuest"] = "Tham quan với tư cách khách",
            ["GuestModeHint"] = "Chế độ khách có giới hạn tính năng. Đăng nhập để mở khóa đầy đủ.",
            ["Version"] = "Phiên bản",
            ["EmailMissing"] = "Thiếu email",
            ["LoginFailed"] = "Đăng nhập thất bại",
            ["LoginCancelled"] = "Đăng nhập đã bị hủy",
            ["GoogleLoginError"] = "Lỗi đăng nhập Google",
            ["Slogan"] = "Khám phá Việt Nam theo cách thông minh nhất",
            // Profile
            ["ExperienceMode"] = "Chế độ trải nghiệm",
            ["ExperienceGuestTitle"] = "Chào bạn!",
            ["ExperienceGuestHint"] = "Hãy đăng nhập để lưu địa điểm và nhận huy hiệu Explorer nhé.",
            ["UpdateAvatarSuccess"] = "Cập nhật ảnh đại diện thành công!",
            ["UpdateProfileSuccess"] = "Cập nhật thông tin thành công!",
            ["UpdateError"] = "Lỗi cập nhật. Vui lòng thử lại.",
            ["EnterFullNameWarning"] = "Vui lòng nhập họ và tên",
            ["PickAvatarTitle"] = "Chọn ảnh đại diện",
            // Home/Filters
            ["AdvancedFilter"] = "Bộ lọc nâng cao",
            ["FindAroundMe"] = "Tìm quanh vị trí của tôi",
            ["MaxDistance"] = "Khoảng cách tối đa",
            ["DestinationStatus"] = "Trạng thái điểm đến",
            ["OpenNow"] = "Đang mở cửa",
            ["HasAudio"] = "Có thuyết minh âm thanh",
            ["FeaturedPlaces"] = "Quán nổi bật",
            ["Reset"] = "Thiết lập lại",
            ["Apply"] = "Áp dụng",
            ["InitError"] = "Lỗi khởi tạo",
            ["LoadCatsError"] = "Lỗi tải danh mục",
            ["LoadPoisError"] = "Lỗi tải địa điểm",
            ["GpsError"] = "Không lấy được vị trí GPS",
            ["GpsPermissionError"] = "Không thể lấy vị trí. Kiểm tra quyền GPS.",
            ["LocationIdentified"] = "Đã xác định vị trí",
            ["RadiusLabel"] = "Bán kính",
            ["SwitchedTo"] = "Đã chuyển",
            // General
            ["PlacesLabel"] = "địa điểm",
            ["PageNotFound"] = "Trang không tồn tại!",
            ["SystemError"] = "Đã xảy ra lỗi hệ thống",
            ["PlacesSavedCount"] = "địa điểm đã lưu",
            ["ViewDetails"] = "Xem chi tiết",
            ["LoadFavsError"] = "Không thể tải danh sách",
            ["DeleteFail"] = "Không thể xóa. Thử lại sau.",
            ["ExploreNow"] = "Khám phá ngay",
            ["ExploreFavDesc"] = "Khám phá và lưu các địa điểm bạn yêu thích để xem lại sau"
        },
        ["en"] = new(StringComparer.OrdinalIgnoreCase) {
            ["Home"] = "Home",
            ["Hello"] = "Hello",
            ["SearchHint"] = "Where do you want to go today?",
            ["Categories"] = "Popular Categories",
            ["All"] = "All",
            ["Featured"] = "Featured Places",
            ["SeeAll"] = "See all",
            ["FindAround"] = "Find around here:",
            ["Details"] = "Details",
            ["NoResults"] = "No places found",
            ["EndList"] = "End of list",
            ["Map"] = "Map",
            ["Profile"] = "Profile",
            ["Scan"] = "Scan QR",
            ["Logout"] = "Logout",
            ["Login"] = "Login",
            ["Introduction"] = "Introduction",
            ["OpeningHours"] = "Opening Hours",
            ["Location"] = "Location",
            ["Direction"] = "Direction",
            ["Audio"] = "Audio",
            ["Share"] = "Share",
            ["Favorite"] = "Favorite",
            ["StartJourney"] = "START JOURNEY",
            ["Updating"] = "Updating content...",
            ["ViewOnMap"] = "View on map",
            ["Coordinates"] = "Coordinates",
            ["Place"] = "Place",
            // Danh mục từ API
            ["Khác"] = "Other",
            ["Quán Bar/Pub"] = "Bar/Pub",
            ["Quán Bar/Club"] = "Bar/Club",
            ["Quán ăn nhanh"] = "Fast Food",
            ["Nhà hàng"] = "Restaurant",
            ["Cà phê"] = "Cafe",
            // Tự động phát
            ["AutoPlayTitle"] = "Auto-Play Commentary",
            ["AutoPlayDesc"] = "Play audio when near POIs",
            // Thứ trong tuần
            ["Monday"] = "Monday",
            ["Tuesday"] = "Tuesday",
            ["Wednesday"] = "Wednesday",
            ["Thursday"] = "Thursday",
            ["Friday"] = "Friday",
            ["Saturday"] = "Saturday",
            ["Sunday"] = "Sunday",
            ["Narrating"] = "Narrating...",
            ["NearbyArea"] = "You are nearby",
            ["Replay"] = "Replay",
            ["ToggleAutoPlay"] = "Auto Play",
            ["FavoriteList"] = "Favorite Places",
            ["JoinDate"] = "Member since",
            ["Active"] = "Active",
            ["PersonalInfo"] = "Personal Information",
            ["Preferences"] = "Settings & Preferences",
            ["Privacy"] = "Privacy & Security",
            ["Support"] = "Support Center",
            ["ChangeAvatarHint"] = "Tap camera to change avatar",
            ["FullNameLabel"] = "Full Name",
            ["FullNameHint"] = "Your name will be displayed on your profile and reviews.",
            ["EmailLabel"] = "Email",
            ["SaveChange"] = "Save Changes",
            ["Saving"] = "Saving...",
            ["LockEmailHint"] = "Email cannot be changed for security.",
            ["Badges"] = "Badges",
            ["EmptyFavs"] = "No favorite places yet",
            ["AppSettings"] = "App Settings",
            ["LoadingMap"] = "Loading Map",
            ["WaitMoment"] = "Please wait a moment...",
            ["MapLoadError"] = "Could not load map",
            ["Retry"] = "Retry",
            ["TokenMissing"] = "Mapbox token is missing.",
            ["LoginToSave"] = "You need to log in to save this place",
            ["LoginNow"] = "Log in now",
            ["SavedToFavs"] = "Saved to favorites",
            ["RemovedFromFavs"] = "Removed from favorites",
            ["LoadPoiError"] = "Could not load place details",
            ["SavePoiError"] = "Error while saving place",
            ["AudioPlayError"] = "Error playing audio",
            ["Listen"] = "Listen",
            ["QRHint"] = "Point camera at QR code for automatic recognition",
            ["CameraUnavailable"] = "Camera unavailable",
            ["QRLoadError"] = "Error loading QR content",
            ["CameraPermission"] = "Please grant Camera permission to scan QR code.",
            ["QROpenError"] = "Failed to open QR scanner",
            ["QRMismatch"] = "System QR code mismatch",
            ["QRNoPoi"] = "No matching content found for this QR.",
            ["BannerPlaying"] = "🔊 Now narrating",
            ["BannerNear"] = "📍 You are near",
            // Auth
            ["WelcomeTitle"] = "Welcome!",
            ["LoginSubtitle"] = "Login to explore amazing places",
            ["Processing"] = "Processing...",
            ["LoginWithGoogle"] = "Login with Google",
            ["Or"] = "OR",
            ["ExploreAsGuest"] = "Explore as a guest",
            ["GuestModeHint"] = "Guest mode has limited features. Login to unlock everything.",
            ["Version"] = "Version",
            ["EmailMissing"] = "Email missing",
            ["LoginFailed"] = "Login failed",
            ["LoginCancelled"] = "Login cancelled",
            ["GoogleLoginError"] = "Google login error",
            ["Slogan"] = "Explore Vietnam in the smartest way",
            // Profile
            ["ExperienceMode"] = "Guest Mode",
            ["ExperienceGuestTitle"] = "Hello!",
            ["ExperienceGuestHint"] = "Login to save places and get Explorer badges.",
            ["UpdateAvatarSuccess"] = "Avatar updated successfully!",
            ["UpdateProfileSuccess"] = "Profile updated successfully!",
            ["UpdateError"] = "Update failed. Please try again.",
            ["EnterFullNameWarning"] = "Please enter your full name",
            ["PickAvatarTitle"] = "Select avatar",
            // Home/Filters
            ["AdvancedFilter"] = "Advanced Filter",
            ["FindAroundMe"] = "Find around my location",
            ["MaxDistance"] = "Maximum distance",
            ["DestinationStatus"] = "Destination status",
            ["OpenNow"] = "Opening now",
            ["HasAudio"] = "Has audio narration",
            ["FeaturedPlaces"] = "Featured places",
            ["Reset"] = "Reset",
            ["Apply"] = "Apply",
            ["InitError"] = "Initialization error",
            ["LoadCatsError"] = "Error loading categories",
            ["LoadPoisError"] = "Error loading places",
            ["GpsError"] = "Could not get GPS location",
            ["GpsPermissionError"] = "Could not get location. Check GPS permissions.",
            ["LocationIdentified"] = "Location identified",
            ["RadiusLabel"] = "Radius",
            ["SwitchedTo"] = "Switched to",
            // General
            ["PlacesLabel"] = "places",
            ["PageNotFound"] = "Page not found!",
            ["SystemError"] = "System error occurred",
            ["PlacesSavedCount"] = "places saved",
            ["ViewDetails"] = "View details",
            ["LoadFavsError"] = "Could not load list",
            ["DeleteFail"] = "Could not delete. Try again later.",
            ["ExploreNow"] = "Explore now",
            ["ExploreFavDesc"] = "Explore and save your favorite places to view them later"
        },
        ["ko"] = new(StringComparer.OrdinalIgnoreCase) {
            ["Home"] = "홈",
            ["Hello"] = "안녕하세요",
            ["SearchHint"] = "오늘은 어디로 가고 싶으신가요?",
            ["Categories"] = "인기 카테고리",
            ["All"] = "전체",
            ["Featured"] = "추천 장소",
            ["SeeAll"] = "전체보기",
            ["FindAround"] = "주변 찾기:",
            ["Details"] = "상세보기",
            ["NoResults"] = "결과를 찾을 수 없습니다",
            ["EndList"] = "리스트의 끝",
            ["Map"] = "지도",
            ["Profile"] = "프로필",
            ["Scan"] = "QR 스캔",
            ["Logout"] = "로그아웃",
            ["Login"] = "로그인",
            ["Introduction"] = "소개",
            ["OpeningHours"] = "영업 시간",
            ["Location"] = "위치",
            ["Direction"] = "길 찾기",
            ["Audio"] = "오디오 가이드",
            ["Share"] = "공유하기",
            ["Favorite"] = "찜하기",
            ["StartJourney"] = "여행 시작하기",
            ["Updating"] = "콘텐츠 업데이트 중...",
            ["ViewOnMap"] = "지도로 보기",
            ["Coordinates"] = "좌표",
            ["Place"] = "장소",
            // Categories
            ["Khác"] = "기타",
            ["Quán Bar/Pub"] = "바/펍",
            ["Quán Bar/Club"] = "바/펍",
            ["Quán ăn nhanh"] = "패스트푸드",
            ["Nhà hàng"] = "레스토랑",
            ["Cà phê"] = "카페",
            // Auto-Play
            ["AutoPlayTitle"] = "자동 음성 안내",
            ["AutoPlayDesc"] = "장소 근처에서 오디오 자동 재생",
            // Days
            ["Monday"] = "월요일",
            ["Tuesday"] = "화요일",
            ["Wednesday"] = "수요일",
            ["Thursday"] = "목요일",
            ["Friday"] = "금요일",
            ["Saturday"] = "토요일",
            ["Sunday"] = "일요일",
            ["Narrating"] = "음성 안내 중...",
            ["NearbyArea"] = "주변에 있습니다",
            ["Replay"] = "다시 듣기",
            ["ToggleAutoPlay"] = "자동 재생",
            ["FavoriteList"] = "즐겨찾기 목록",
            ["JoinDate"] = "가입일",
            ["Active"] = "활동 중",
            ["PersonalInfo"] = "개인 정보",
            ["Preferences"] = "설정 및 기본 설정",
            ["Privacy"] = "개인 정보 보호",
            ["Support"] = "고객 센터",
            ["ChangeAvatarHint"] = "사진을 변경하려면 카메라를 누르세요",
            ["FullNameLabel"] = "성명",
            ["FullNameHint"] = "귀하의 이름은 프로필 및 리뷰에 표시됩니다.",
            ["EmailLabel"] = "이메일",
            ["SaveChange"] = "변경 사항 저장",
            ["Saving"] = "저장 중...",
            ["LockEmailHint"] = "보안을 위해 이메일은 변경할 수 없습니다.",
            ["Badges"] = "배지",
            ["EmptyFavs"] = "아직 즐겨찾는 장소가 없습니다",
            ["AppSettings"] = "앱 설정",
            ["LoadingMap"] = "지도를 불러오는 중",
            ["WaitMoment"] = "잠시만 기다려 주세요...",
            ["MapLoadError"] = "지도를 불러올 수 없습니다",
            ["Retry"] = "다시 시도",
            ["TokenMissing"] = "Mapbox 토큰이 없습니다.",
            ["LoginToSave"] = "이 장소를 저장하려면 로그인이 필요합니다",
            ["LoginNow"] = "지금 로그인",
            ["SavedToFavs"] = "즐겨찾기에 저장됨",
            ["RemovedFromFavs"] = "즐겨찾기에서 삭제됨",
            ["LoadPoiError"] = "장소 상세 정보를 불러올 수 없습니다",
            ["SavePoiError"] = "장소 저장 중 오류 발생",
            ["AudioPlayError"] = "오디오 재생 중 오류 발생",
            ["Listen"] = "듣기",
            ["QRHint"] = "자동 인식을 위해 QR 코드를 뷰파인더에 맞추세요",
            ["CameraUnavailable"] = "카메라를 사용할 수 없음",
            ["QRLoadError"] = "QR 콘텐츠를 불러오는 중 오류 발생",
            ["CameraPermission"] = "QR 코드를 스캔하려면 카메라 권한을 허용해 주세요.",
            ["QROpenError"] = "QR 스캐너를 열지 못했습니다",
            ["QRMismatch"] = "시스템 QR 코드가 일치하지 않습니다",
            ["QRNoPoi"] = "이 QR에 해당하는 콘텐츠를 찾을 수 없습니다.",
            ["BannerPlaying"] = "🔊 현재 안내 중",
            ["BannerNear"] = "📍 근처에 있습니다",
            // Auth
            ["WelcomeTitle"] = "환영합니다!",
            ["LoginSubtitle"] = "놀라운 장소를 탐험하기 위해 로그인하세요",
            ["Processing"] = "처리 중...",
            ["LoginWithGoogle"] = "Google로 로그인",
            ["Or"] = "또는",
            ["ExploreAsGuest"] = "게스트로 탐색",
            ["GuestModeHint"] = "게스트 모드는 기능이 제한됩니다. 모든 기능을 이용하려면 로그인하세요.",
            ["Version"] = "버전",
            ["EmailMissing"] = "이메일 누락",
            ["LoginFailed"] = "로그인 실패",
            ["LoginCancelled"] = "로그인 취소됨",
            ["GoogleLoginError"] = "Google 로그인 오류",
            ["Slogan"] = "가장 스마트한 방법으로 베트남을 탐험하세요",
            // Profile
            ["ExperienceMode"] = "게스트 모드",
            ["ExperienceGuestTitle"] = "안녕하세요!",
            ["ExperienceGuestHint"] = "장소를 저장하고 Explorer 배지를 받으려면 로그인하세요.",
            ["UpdateAvatarSuccess"] = "프로필 사진이 업데이트되었습니다!",
            ["UpdateProfileSuccess"] = "프로필이 성공적으로 업데이트되었습니다!",
            ["UpdateError"] = "업데이트 실패. 다시 시도해 주세요.",
            ["EnterFullNameWarning"] = "이름을 입력해 주세요",
            ["PickAvatarTitle"] = "프로필 사진 선택",
            // Home/Filters
            ["AdvancedFilter"] = "고급 필터",
            ["FindAroundMe"] = "내 위치 주변 찾기",
            ["MaxDistance"] = "최대 거리",
            ["DestinationStatus"] = "목적지 상태",
            ["OpenNow"] = "현재 영업 중",
            ["HasAudio"] = "오디오 가이드 있음",
            ["FeaturedPlaces"] = "추천 장소",
            ["Reset"] = "초기화",
            ["Apply"] = "적용",
            ["InitError"] = "초기화 오류",
            ["LoadCatsError"] = "카테고리 로드 오류",
            ["LoadPoisError"] = "장소 로드 오류",
            ["GpsError"] = "GPS 위치를 가져올 수 없습니다",
            ["GpsPermissionError"] = "위치를 가져올 수 없습니다. GPS 권한을 확인하세요.",
            ["LocationIdentified"] = "위치 확인됨",
            ["RadiusLabel"] = "반경",
            ["SwitchedTo"] = "전환됨",
            // General
            ["PlacesLabel"] = "개소",
            ["PageNotFound"] = "페이지를 찾을 수 없습니다!",
            ["SystemError"] = "시스템 오류가 발생했습니다",
            ["PlacesSavedCount"] = "곳의 저장된 장소",
            ["ViewDetails"] = "상세 보기",
            ["LoadFavsError"] = "목록을 불러올 수 없습니다",
            ["DeleteFail"] = "삭제할 수 없습니다. 나중에 다시 시도하세요.",
            ["ExploreNow"] = "지금 탐색하기",
            ["ExploreFavDesc"] = "좋아하는 장소를 탐색하고 저장하여 나중에 다시 확인하세요"
        }

        // Bạn có thể thêm ["fr"], ["jp"] vào đây cực kỳ dễ dàng
    };

    public void SetLanguage(string languageCode)
    {
        if (SelectedLanguage != languageCode)
        {
            SelectedLanguage = languageCode;
            OnLanguageChanged?.Invoke();
        }
    }

    // Hàm lấy bản dịch tự động
    public string T(string key)
    {
        if (_translations.ContainsKey(SelectedLanguage) && _translations[SelectedLanguage].ContainsKey(key))
        {
            return _translations[SelectedLanguage][key];
        }
        
        // Nếu không tìm thấy ngôn ngữ đang chọn, thử lấy tiếng Việt
        if (_translations["vi"].ContainsKey(key)) return _translations["vi"][key];
        
        return key; // Cùng lắm trả về chính cái key đó
    }
}
